Update recipe.

diff --git a/recipes/recipe.yml b/recipes/recipe.yml
--- a/recipes/recipe.yml
+++ b/recipes/recipe.yml
@@ -28,7 +28,6 @@ modules:
 
         # Virtualization Tools
         - virt-manager # Virtual Machine Manager GUI
-        - qemu-kvm # QEMU and KVM
         - libvirt # Virtualization library and daemon
         - virt-install # Command line tool for installing VMs
 
@@ -104,6 +103,19 @@ modules:
 #      enabled:
 #        - gdm.service
 #        - libvirtd.service
+
+  - type: script
+    snippets:
+      # Create the gdm user and group, which dnf install won't do
+      - |
+        set -euxo pipefail # Exit immediately if a command fails
+        # Create the gdm group if it doesn't exist
+        if ! getent group gdm > /dev/null; then
+          groupadd -r gdm
+        fi
+        # Create the gdm user if it doesn't exist
+        if ! getent passwd gdm > /dev/null; then
+          useradd -r -g gdm -d /var/lib/gdm -s /usr/sbin/nologin -c "GNOME Display Manager daemon user" gdm
 
   - type: kargs
     kargs:
